### ISSUE TITLE
Test against Python 3.7

### ISSUE THREAD

**Issue by rbarrois** [django-ldapdb/django-ldapdb#165]
#### The problem
``django-ldapdb`` should be tested against python 3.7.

#### Extra notes
There might be some issues with configuring Travis-CI with python 3.7.

#### Checklist:

- [x] Add the target to ``tox.ini``
- [x] Add that target to ``.travis.yml``
- [x] Update the trove classifiers in ``setup.py``
- [x] Update the list of supported version in the docs

**Comment by Natureshadow** [comment]
For the record: Travis cannot be done yet because of https://github.com/travis-ci/travis-ci/issues/9815

**Comment by Natureshadow** [comment]
Merging #167 once travis supports Python 3.7 will close this issue.

**Comment by xavfernandez** [comment]
This can be closed :)

**Comment by rbarrois** [comment]
Indeed ;)
